# TP2 - Géométrie épipolaire
L'objectif de ce TP est de se focaliser sur les éléments de base de la
géométrie épipolaire. A l’aide des fonctions fournies dans le fichier utils.py,
dans le fichier utils_to_complete.py compléter à partir du cours les fonctions
utilitaires suivantes :
- inverseHomogeneousMatrix()
- mulMplyHomogeneousMatrix()
- skew()

![Texte alternatif](images/image.png)


In [7]:
import numpy as np
from utils_to_complete_etudiant import inverseHomogeneousMatrix, multiplyHomogeneousMatrix, skew

In [3]:
# Test inverseHomogeneousMatrix
T = np.array([[1, 0, 0, 3],
              [0, 1, 0, 4],
              [0, 0, 1, 5],
              [0, 0, 0, 1]])

inv_T = inverseHomogeneousMatrix(T)
print("Inverse of Homogeneous Matrix:")
print(inv_T)

Inverse of Homogeneous Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# Test multiplyHomogeneousMatrix
T1 = np.array([[1, 0, 0, 2],
               [0, 1, 0, 3],
               [0, 0, 1, 4],
               [0, 0, 0, 1]])

T2 = np.array([[1, 0, 0, 5],
               [0, 1, 0, 6],
               [0, 0, 1, 7],
               [0, 0, 0, 1]])

T12 = multiplyHomogeneousMatrix(T1, T2)
print("\nProduct of Two Homogeneous Matrices:")
print(T12)



Product of Two Homogeneous Matrices:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# Test skew
t = np.array([1, 2, 3])
sk_matrix = skew(t)
print("\nSkew Symmetric Matrix:")
print(sk_matrix)


Skew Symmetric Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Soit un système stéréoscopique donnant deux images I1 et I2. La calibration des caméras est connue. On supposera dans un premier temps que la matrice de calibration est donnée par :

$$

K = \begin{pmatrix} 

800 & 0 & 200 \\ 

0 & 800 & 150 \\ 

0 & 0 & 1 

\end{pmatrix} 

$$




## Question 1: A quoi correspondent les valeurs dans la matrice K?
- --->Dans un système stéréoscopique, chaque caméra est caractérisée par une matrice de calibration qui contient des paramètres internes essentiels pour la transformation des coordonnées du monde réel en coordonnées de l'image. Cette transformation permet de projeter les objets 3D dans l'espace vers des coordonnées 2D sur l'image.

- Matrice de calibration \( K \)

La matrice de calibration pour notre caméra est donnée par :

$$
K = \begin{pmatrix}
800 & 0 & 200 \\
0 & 800 & 150 \\
0 & 0 & 1
\end{pmatrix}
$$

- Explication des éléments de la matrice \( K \)

La matrice \( K \) contient plusieurs valeurs clés qui décrivent les caractéristiques intrinsèques de la caméra.

1. **\( fx = 800 \)** : Facteur de mise à l'échelle en pixels le long de l'axe \( x \), ce qui est lié à la focale de la caméra et à la taille des pixels du capteur.
2. **\( fy = 800 \)** : Facteur de mise à l'échelle en pixels le long de l'axe \( y \), similaire à \( fx \), indiquant l'échelle en pixels sur l'axe vertical de l'image.
3. **\( cx = 200 \)** : Coordonnée du centre de l'image sur l'axe \( x \), indiquant où se trouve le point principal (le centre optique) de la caméra sur l'image horizontale.
4. **\( cy = 150 \)** : Coordonnée du centre de l'image sur l'axe \( y \), indiquant le point central de l'image verticale.
5. **\( 1 \)** : Cette valeur permet de rendre la matrice homogène, ce qui est nécessaire pour les calculs en coordonnées homogènes.

- Nous supposerons que la caméra c2 est positionnée à la position c2Tw définie par (voir Figure 1):

$$
c^2Tw = \begin{bmatrix} 
1 & 0 & 0 & 0 \\ 
0 & 1 & 0 & 0 \\ 
0 & 0 & 1 & 2 \\ 
0 & 0 & 0 & 1 
\end{bmatrix}
$$


![Texte alternatif](images/image2.png)


## Cas 1 : La caméra c1 est positionnée 10 cm à gauche de c2.
-  **Question 2: Donner la matrice c1Tw. En utilisant le squelette de code mis à votre disposition, compléter la matrice c1Tw.**
Since camera $c_1$ is positioned 10 cm (or 0.1 meters) to the left of $c_2$, the transformation matrix ${}^{c1}T_w$ will reflect this translation along the $x$-axis. Assuming no rotation, the matrix ${}^{c1}T_w$ is:

$$
{}^{c1}T_w =
\begin{pmatrix}
1 & 0 & 0 & -0.1 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 2 \\
0 & 0 & 0 & 1 
\end{pmatrix}
$$

In this matrix:

- The $0.$ in the $(1, 4)$ position indicates a 10 cm leftward translation of $c_1$ relative to $c_2$ along the $x$-axis.
- The $2$ in the $(3, 4)$ position represents the $z$-axis translation of both cameras (since they are both positioned 2 units from the world origin along $z$).

- **Question 3: Comment appelle-t-on un tel système et préciser ?**
On souhaite pouvoir faciliter la mise en correspondance de points dans les deux images. Pour cela, on s'attachera à représenter le lieu géométrique d'un point x1 dans l'image 11 où son correspondant x2 dans 12 peut se situer.

*We aim to facilitate point matching between the two images. To do this, we will represent the geometric location of a point $x_1$ in image $I_1$, where its corresponding point $x_2$ in $I_2$ might be located.*
- **Question 4: Caractériser ce lieu. Calculer son équation. Dans le rapport, donner les coordonnées des points x1 pour les points x2 (100,100) et (50, 75).**
- **Question 5: Afficher les points x2 dans 12 et les lieus calculés précédemment dans 11. Vérifier que vous obtenez bien le résultat attendu et donner l'image obtenue.**

## Cas 2: Positionner maintenant la caméra c1 20 cm devant c2.
- **Question 6 : Donner la nouvelle matrice c1Tw. Question**
- **Question 7 : Quelle est la position de l'épipôle ?**
- **Question 8: Refaire pour cette nouvelle position les questions 4 et 5.**


## Cas 3: Positionner maintenant la caméra c1 en c1Tw tel que la translation vaut (0.1, 0, 1.9) et la rotation en degrés (5, 5, 5) en utilisant la représentation minimale angle-axe aussi appelée theta-u.
- **Question 9: Donner la nouvelle matrice c1Tw.**
- **Question 10: Donner la nouvelle position des épipôles.**
- **Question 11: Refaire pour cette nouvelle position les questions 4 et 5.**